### PR TITLE
Port to material-ui v1 beta

### LINKED ISSUE #25: Port to material-ui 1.0.0-beta
So, im getting 
Module not found: Can't resolve 'material-ui/svg-icons/navigation/arrow-back' in 'C:\Users\Pedro\tt\node_modules\material-auto-rotating-carousel\lib'

I'm using material-ui last version, should i use a previous one?

### PR DESCRIPTION
**Pull request by chaitan94**
This should hopefully fix #25 

Cheers,
chaitan94

### CODE REVIEW

**Comment by leMaik** [comment]
It's a very good start, thank you very much! :heart: 
I'll continue the work on your branch soon!

**Comment by m2mathew** [comment]
@leMaik Have you had a chance to review this PR? I was about to port this over to v1 for one of our CEA projects, but realized that @chaitan94 had already started the work. Thanks!

**Comment by leMaik** [comment]
@m2mathew This PR is now outdated (plenty of breaking changes in material-ui) and not done yet. If you want, we'd really like to see this work to be continued! :100: 

Otherwise, I'll port it as soon as I've got time. There is a project where we might need this component later.

**Comment by m2mathew** [comment]
Yeah, I was about 15 versions behind on MUI beta. API is much different, but feels great to use. I might have time to dig back into this soon!

**Comment by leMaik** [comment]
I'll close this in favor of #35

**Pull request closed without merging**
