### PR TITLE
making button optional

### PR DESCRIPTION
**Pull request by leebailey88**
This fixes issue #17 that I raised about enabling a more minimal use case of the carousel by making the button optional.

@leMaik

### CODE REVIEW

**Comment by leMaik** [comment]
The original idea was to only support the use case of using this as intended by the Material UI specs. But since this feature is basically free, I'm ok with it, thanks for the PR! :+1: 

Would you mind updating the README and remove `.required` from [the label prop](https://github.com/TeamWertarbyte/material-auto-rotating-carousel/blob/master/src/AutoRotatingCarousel.js#L251)? Also, we should add a note that the button will be hidden if no label is specified.

**Comment by leebailey88** [comment]
@leMaik thanks for reviewing quickly, I made the suggested changes to the readme file and squashed my commits

**Comment by leMaik** [comment]
Awesome, @leebailey88! I'll merge it soon.

**Comment by leMaik** [comment]
Thanks again for the PR, I'll publish an update asap. :tada:

**Pull request merged**
