### PR TITLE
Fixes for stable material-ui-next 1.0.0 release

### PR DESCRIPTION
**Pull request by kuus**

### CODE REVIEW

**Comment by leMaik** [comment]
@kuus  Thank you very much, this is a great first contribution. :+1: 

This PR targets the wrong branch, though. I'll close it and merge your branch into our `next` branch. Don't worry, you'll keep the commits and you'll still be mentioned in the changelog. :sunglasses:

**Comment by kuus** [comment]
but mostly thanks to you @leMaik  for your nice work! (sorry I got confused with the branch)

**Comment by leMaik** [comment]
Yeah, our branches are pretty confusing right now. We are re-doing them in all components, `master` for the material-ui@1.0.0 version and `legacy` for the 0.x version. Will take a few days until that's done.

**Comment by kuus** [comment]
well done! would you bump the npm version of the package perhaps?

**Comment by leMaik** [comment]
Working on that. :hourglass: I'll update the readme, babel config, …

**Comment by leMaik** [comment]
Done: https://github.com/TeamWertarbyte/material-auto-rotating-carousel/releases/tag/v2.0.0

**Pull request closed without merging**
